# This is an example of advanced Docker Compose deployment for Imgcompress
# with more settings & some best practices in common for deploying containers.

# Placing anchors for default options
# so we can reuse them in multiple Docker services
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "10"
    compress: "true"
x-healthcheck: &default-healthcheck
  interval: 3s
  retries: 10
  timeout: 3s
  start_period: 10s

# Isolated network to prevent other services on Docker host seeing it.
# By default, Docker attachs 50 bytes header to routing network packets into container.
# Lower MTU to 1450, so 1450 + 50 from Docker = 1500 (which is the standard MTU)
networks:
  imgcompress-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

services:
  imgcompress:
    image: ${IMGCOMPRESS_REGISTRY:-karimz1/imgcompress}:${IMGCOMPRESS_TAG:-latest}
    container_name: imgcompress
    restart: always
    ports:
      # Only expose to localhost by default to prevent unintented public access.
      # If you want to access from another machine, set IMGCOMPRESS_HOST=0.0.0.0 in `.env` file.
      - "${IMGCOMPRESS_HOST:-127.0.0.1}:${IMGCOMPRESS_PORT:-3001}:5000"
    environment:
      # Set to true to remove the mascot and enable a minimal, mascot-free UI
      - DISABLE_LOGO=${IMGCOMPRESS_DISABLE_LOGO:-false}
      # Set to true to disable the storage management features (e.g., for your users to not see all the files)
      - DISABLE_STORAGE_MANAGEMENT=${IMGCOMPRESS_DISABLE_STORAGE_MANAGEMENT:-false}
    healthcheck:
      test: ["CMD", "python", "/container/healthcheck.py"]
      <<: *default-healthcheck
    # Prevent container from causing Docker host run out of file descriptors
    # (default limit of Linux is 65535)
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    # Allow cotainer to shut down gracefully, instead of let Docker calls SIGTERM killing it.
    stop_grace_period: 15s
    # Prevent container from gaining new privileges (container breakout)
    security_opt:
      - no-new-privileges:true
    logging:
      <<: *default-logging
