name: Docker in Docker CI

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
    docker:
      image: docker:dind
      options: --privileged
      env:
        DOCKER_TLS_CERTDIR: ""


    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set Docker host
        run: echo "DOCKER_HOST=tcp://localhost:2375" >> $GITHUB_ENV

      - name: Docker version
        run: docker version

      - name: Build devcontainer image
        run: docker build -t devcontainer:local-test .

      #- name: Run your nested test
       # run: ./runTests.sh
