name: Docker in Docker CI

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged
        env:
          DOCKER_TLS_CERTDIR: ""
        ports:
          - 2375:2375

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Wait for Docker daemon to be ready
        run: |
          until docker info > /dev/null 2>&1; do
            echo "Waiting for Docker daemon..."
            sleep 1
          done

      - name: Verify Docker version
        run: docker version

      - name: Build Docker image
        run: docker build -t devcontainer:local-test -f .devcontainer/Dockerfile .

      - name: Test container
        run: |
          docker run --rm \
           -e DOCKER_HOST=tcp://localhost:2375 \
           devcontainer:local-test /app/runTests.sh
