name: Docker in Docker CI

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install tree
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: List Repository Contents
        run: |
          echo "===== Root Directory ====="
          pwd
          tree -L 2
          echo "===== End Root Directory ====="

          echo "===== tests Directory ====="
          if [ -d "tests" ]; then
            cd tests
            pwd
            tree -L 2
            cd ..
          else
            echo "tests directory does not exist."
          fi
          echo "===== End tests Directory ====="


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build --no-cache -t devcontainer:local-test -f .devcontainer/Dockerfile .

      - name: Run Tests
        run: |
          docker run --rm \
            -v "/workspace/tests/sample-images:/app/input_folder" \
            -v "/workspace/tests/output:/app/output_folder" \
            devcontainer:local-test /app/runTests.sh 2>&1 | tee docker_run.log
        continue-on-error: true

      - name: Upload Docker Run Logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: docker-run-logs
          path: docker_run.log

      - name: Check Test Results
        if: failure()
        run: |
          echo "Docker run failed. Displaying logs:"
          cat docker_run.log
          exit 1

