name: Test and Coverage

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest pytest-cov

      - name: Run Pytest and Generate Reports
        run: |
          chmod -R u+r tests/
          chmod 755 ./runTests.sh
          ./runTests.sh

      - name: Upload Pytest Report
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: reports/test-results.xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: reports/test-coverage.xml
