name: Docker in Docker CI

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged
        env:
          DOCKER_TLS_CERTDIR: ""
        ports:
          - 2375:2375

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Verify Docker version
        run: docker version

      - name: Build Docker image
        run: docker build -t devcontainer:local-test -f .devcontainer/Dockerfile .

      - name: Test container
        run: docker run --rm devcontainer:local-test ./runTests.sh
